[env]
RUSTFLAGS = "-A dead_code"

[tasks.test]
command = "cargo"
args = ["test", "--lib"]

[tasks.verbose-test]
command = "cargo"
args = ["test", "--lib", "--", "--nocapture"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]
