name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: davidB/rust-cargo-make@v1
    - name: Build
      run: cargo make build 
    - name: Run formatter
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo make clippy
    - name: Run tests
      run: cargo make test
    - name: Just run everything 
      run: cargo make check-everything 
